name: 'Get GitHub Custom Metadata'
description: 'Get custom metadata from a GitHub issue that previously had metadata stored in the OP'
inputs:
  issue_number:
    description: 'The issue body to get a value from'
    required: false
  key:  # id of input
    description: 'The Key for the value to be retrived'
    required: true
  myToken:  # id of input
    description: 'The token for access'
    required: true
#  getArray:  # id of input
#    description: 'Set to true to return the entire metadata object'
#    required: false
#    default: false
outputs:
  result:
    description: 'The value returned'
runs:
  using: 'node12'
  main: 'dist/index.js'
