name: 'Get GitHub Custom Metadata'
description: 'Get custom metadata from a GitHub issue that previously had metadata stored in the OP'
inputs:
  key:  # id of input
    description: 'The Key for the value to be retrived'
    required: true
  myToken:  # id of input
    description: 'The token for access'
    required: true
outputs:
   value:
     description: 'The returned value'
runs:
  using: 'node12'
  main: 'dist/index.js'
